export const precios = {
  ZonaAlta: [
    { nombre: "Rostro", precio: 15079 },
    { nombre: "Bozo", precio: 6598 },
    { nombre: "Menton", precio: 6598 },
    { nombre: "Patillas", precio: 6598 },
    { nombre: "Frente", precio: 6598 },
    { nombre: "Pomulos", precio: 6598 },
    { nombre: "Nariz", precio: 6598 },
    { nombre: "Entrecejo", precio: 6598 },
    { nombre: "Pabellon Auricular", precio: 6598 },
    { nombre: "Cuello Frontal", precio: 6598 },
    { nombre: "Cuello Posterior (nuca)", precio: 6598 },
  ],
  ZonaMedia: [
    { nombre: "Hombros", precio: 6598 },
    { nombre: "Escote", precio: 6598 },
    { nombre: "Espalda Completa", precio: 16517 },
    { nombre: "Espalda Superior", precio: 6598 },
    { nombre: "Espalda Media", precio: 6598 },
    { nombre: "Espalda Inferior", precio: 6598 },
    { nombre: "Pecho/Torax", precio: 10048 },
    { nombre: "Abdomen", precio: 8611 },
    { nombre: "Medio Abdomen", precio: 6598 },
    { nombre: "Linea Alba", precio: 6598 },
    { nombre: "Areolas", precio: 6598 },
    { nombre: "Antebrazo", precio: 10048 },
    { nombre: "Brazo Superior", precio: 10048 },
    { nombre: "Brazo Completo", precio: 14361 },
    { nombre: "Manos", precio: 6598 },
  ],
  ZonaBaja: [
    { nombre: "Pelvis", precio: 7892 },
    { nombre: "Pelvis y Genitales", precio: 12204 },
    { nombre: "Gluteos", precio: 11486 },
    { nombre: "Medio Gluteo", precio: 6598 },
    { nombre: "Muslos", precio: 15079 },
    { nombre: "Muslo Anterior", precio: 10767 },
    { nombre: "Muslo Posterior", precio: 10767 },
    { nombre: "Muslos Cara Interna", precio: 6598 },
    { nombre: "Pierna Entera", precio: 25717 },
    { nombre: "Media Pierna Inf", precio: 15079 },
    { nombre: "Rodillas", precio: 6598 },
    { nombre: "Pies", precio: 6598 },
    { nombre: "Cavado Completo", precio: 14792 },
    { nombre: "Tira de Cola", precio: 6598 },
  ],
};
